### ISSUE TITLE
Display all existing AEX-9 tokens as a subcategory

### ISSUE THREAD

**Issue by jdgcs** [jdgcs/aeknow#29]
Thanks Erik: https://forum.aeternity.com/t/active-aeknow-org-improvements-and-aeknow-chain-development-proposal/7001/29

**Comment by ErkanKanden** [comment]
Any updates here?

**Comment by jdgcs** [comment]
> Any updates here?

https://www.aeknow.org/token

done~feedbacks are welcome!
